In [1]:
#Импортируем необходимые библиотеки 
import pandas as pd
import numpy as np

In [2]:
#С попомощью библиотеки pandas загружвем csv-файл
powerlift=pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-08/ipf_lifts.csv', decimal=',')

In [3]:
#Озанкомление с датафреймом, просмотр первых 15 строк
powerlift.head(15)

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205,140,225,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24,24-34,NaN,67.5,67.5,225,132.5,235,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,NaN,67.5,67.5,245,157.5,270,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,NaN,67.5,67.5,195,110,240,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,240,140,215,5,1985-08-03,IPF,World Games
5,PJ Joseph,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,200,100,230,6,1985-08-03,IPF,World Games
6,Wilfried Dörner,M,SBD,Single-ply,32.5,24-34,NaN,67.5,67.5,220,140,235,7,1985-08-03,IPF,World Games
7,Claudio Ardini,M,SBD,Single-ply,31.5,24-34,NaN,90,90,295,215,335,1,1985-08-03,IPF,World Games
8,Eric Copping,M,SBD,Single-ply,NaN,NaN,NaN,90,90,282.5,162.5,310,2,1985-08-03,IPF,World Games
9,Glen Waszkiel,M,SBD,Single-ply,NaN,NaN,NaN,90,90,285,167.5,295,2,1985-08-03,IPF,World Games
10,Jarmo Virtanen,M,SBD,Single-ply,NaN,NaN,NaN,90,90,295,175,315,3,1985-08-03,IPF,World Games
11,Mike Duffy,M,SBD,Single-ply,NaN,NaN,NaN,90,90,285,185,290,4,1985-08-03,IPF,World Games
12,Tokiharu Maeda,M,SBD,Single-ply,40.5,40-44,NaN,90,90,320,170,300,5,1985-08-03,IPF,World Games
13,Tony Stevens,M,SBD,Single-ply,NaN,NaN,NaN,NaN,90+,355,225,350,1,1985-08-03,IPF,World Games
14,Dave Caldwell,M,SBD,Single-ply,36.5,35-39,NaN,NaN,90+,350,212.5,300,2,1985-08-03,IPF,World Games

In [4]:
#Озанкомление с датафреймом, просмотр последних 15 строк
powerlift.tail(15)

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
41137,Mario Böttcher,M,B,Single-ply,NaN,NaN,Open,136.7,125+,NaN,250,NaN,DD,1995-06-25,IPF,World Bench Press Championships
41138,Troy McNett,M,B,Single-ply,NaN,NaN,Open,150,125+,NaN,245,NaN,3,1995-06-25,IPF,World Bench Press Championships
41139,Rif Gadiev,M,B,Single-ply,30.5,24-34,Open,138.1,125+,NaN,242.5,NaN,4,1995-06-25,IPF,World Bench Press Championships
41140,Peder,M,B,Single-ply,NaN,NaN,Open,135.8,125+,NaN,230,NaN,5,1995-06-25,IPF,World Bench Press Championships
41141,Lajos Bajos,M,B,Single-ply,NaN,NaN,Open,132.2,125+,NaN,225,NaN,6,1995-06-25,IPF,World Bench Press Championships
41142,Antonín Šota,M,B,Single-ply,NaN,NaN,Open,138.9,125+,NaN,222.5,NaN,7,1995-06-25,IPF,World Bench Press Championships
41143,Ichiro Ujiie,M,B,Single-ply,37.5,35-39,Open,132.2,125+,NaN,220,NaN,8,1995-06-25,IPF,World Bench Press Championships
41144,Piotr Pawlik,M,B,Single-ply,39.5,35-39,Open,127,125+,NaN,215,NaN,9,1995-06-25,IPF,World Bench Press Championships
41145,Huhtakangas,M,B,Single-ply,NaN,NaN,Open,126.1,125+,NaN,205,NaN,10,1995-06-25,IPF,World Bench Press Championships
41146,Vasyl' Orobets,M,B,Single-ply,28.5,24-34,Open,146.9,125+,NaN,205,NaN,11,1995-06-25,IPF,World Bench Press Championships
41147,Chien-Hsiung Chao,M,B,Single-ply,NaN,NaN,Open,126.5,125+,NaN,202.5,NaN,12,1995-06-25,IPF,World Bench Press Championships
41148,Oleg Gordynetz,M,B,Single-ply,NaN,NaN,Open,137.5,125+,NaN,202.5,NaN,13,1995-06-25,IPF,World Bench Press Championships
41149,Clive Lambert,M,B,Single-ply,31.5,24-34,Open,142.2,125+,NaN,202.5,NaN,14,1995-06-25,IPF,World Bench Press Championships
41150,Peter Brath,M,B,Single-ply,21.5,20-23,Open,125.5,125+,NaN,180,NaN,15,1995-06-25,IPF,World Bench Press Championships
41151,Valery Sidorenko,M,B,Single-ply,38.5,35-39,Open,142,125+,NaN,NaN,NaN,DQ,1995-06-25,IPF,World Bench Press Championships

In [5]:
#Озанкомление с типами данных в датафрейме
powerlift.info('Dtype')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41152 entries, 0 to 41151
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              41152 non-null  object
 1   sex               41152 non-null  object
 2   event             41152 non-null  object
 3   equipment         41152 non-null  object
 4   age               38246 non-null  object
 5   age_class         38268 non-null  object
 6   division          40525 non-null  object
 7   bodyweight_kg     40965 non-null  object
 8   weight_class_kg   41151 non-null  object
 9   best3squat_kg     27454 non-null  object
 10  best3bench_kg     38690 non-null  object
 11  best3deadlift_kg  27124 non-null  object
 12  place             41152 non-null  object
 13  date              41152 non-null  object
 14  federation        41152 non-null  object
 15  meet_name         41152 non-null  object
dtypes: object(16)
memory usage: 5.0+ MB

In [6]:
#Проверяем дата фрейм на пустые значение 
powerlift.isna().sum()

name                    0
sex                     0
event                   0
equipment               0
age                  2906
age_class            2884
division              627
bodyweight_kg         187
weight_class_kg         1
best3squat_kg       13698
best3bench_kg        2462
best3deadlift_kg    14028
place                   0
date                    0
federation              0
meet_name               0
dtype: int64

In [7]:
#Просмотр количетва уникальных значений по каждой колонке
powerlift.nunique()

name                17803
sex                     2
event                   3
equipment               3
age                   150
age_class              16
division               12
bodyweight_kg        6482
weight_class_kg        38
best3squat_kg         353
best3bench_kg         402
best3deadlift_kg      316
place                  34
date                  224
federation              1
meet_name              30
dtype: int64

In [8]:
#Просмотр размерности датафрейма
powerlift.shape

(41152, 16)

In [9]:
#Просмотр общей статистики по датафрейму
powerlift.describe()

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
count,41152,41152,41152,41152,38246,38268,40525,40965,41151,27454,38690,27124,41152,41152,41152,41152
unique,17803,2,3,3,150,16,12,6482,38,353,402,316,34,224,1,30
top,Hiroyuki Isagawa,M,SBD,Single-ply,22.5,24-34,Open,75,82.5,220,150,250,1,2019-05-18,IPF,World Bench Press Championships
freq,54,27900,28586,33309,2417,9505,16517,452,2768,618,820,654,6480,1060,41152,7193

In [10]:
# Заполнить пустые значения нулями исходя из доступных данных
powerlift.fillna(0)

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,0,0,0,67.5,67.5,205,140,225,1,1985-08-03,IPF,World Games
1,David Mannering,M,SBD,Single-ply,24,24-34,0,67.5,67.5,225,132.5,235,2,1985-08-03,IPF,World Games
2,Eddy Pengelly,M,SBD,Single-ply,35.5,35-39,0,67.5,67.5,245,157.5,270,3,1985-08-03,IPF,World Games
3,Nanda Talambanua,M,SBD,Single-ply,19.5,20-23,0,67.5,67.5,195,110,240,4,1985-08-03,IPF,World Games
4,Göran Henrysson,M,SBD,Single-ply,0,0,0,67.5,67.5,240,140,215,5,1985-08-03,IPF,World Games
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41147,Chien-Hsiung Chao,M,B,Single-ply,0,0,Open,126.5,125+,0,202.5,0,12,1995-06-25,IPF,World Bench Press Championships
41148,Oleg Gordynetz,M,B,Single-ply,0,0,Open,137.5,125+,0,202.5,0,13,1995-06-25,IPF,World Bench Press Championships
41149,Clive Lambert,M,B,Single-ply,31.5,24-34,Open,142.2,125+,0,202.5,0,14,1995-06-25,IPF,World Bench Press Championships
41150,Peter Brath,M,B,Single-ply,21.5,20-23,Open,125.5,125+,0,180,0,15,1995-06-25,IPF,World Bench Press Championships
41151,Valery Sidorenko,M,B,Single-ply,38.5,35-39,Open,142,125+,0,0,0,DQ,1995-06-25,IPF,World Bench Press Championships

In [11]:
#Преобразовуем в числовой тип
powerlift['best3squat_kg'] = pd.to_numeric(powerlift['best3squat_kg'],errors = 'coerce')

In [12]:
#Преобразовуем в числовой тип
powerlift['best3deadlift_kg'] = pd.to_numeric(powerlift['best3deadlift_kg'],errors = 'coerce')

In [13]:
#Преобразовуем в числовой тип
powerlift['best3bench_kg'] = pd.to_numeric(powerlift['best3bench_kg'],errors = 'coerce')

In [14]:
#Проверяем изменения типа
powerlift.info('Dtype')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41152 entries, 0 to 41151
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              41152 non-null  object
 1   sex               41152 non-null  object
 2   event             41152 non-null  object
 3   equipment         41152 non-null  object
 4   age               38246 non-null  object
 5   age_class         38268 non-null  object
 6   division          40525 non-null  object
 7   bodyweight_kg     40965 non-null  object
 8   weight_class_kg   41151 non-null  object
 9   best3squat_kg     27454 non-null  float64
 10  best3bench_kg     38690 non-null  float64
 11  best3deadlift_kg  27124 non-null  float64
 12  place             41152 non-null  object
 13  date              41152 non-null  object
 14  federation        41152 non-null  object
 15  meet_name         41152 non-null  object
dtypes: float64(3), object(13)
memory usage: 5.0+ MB

In [15]:
#Рекорды каждого пола
powerlift.groupby('sex').agg({
  "best3squat_kg": "max",
  "best3bench_kg": "max",
  "best3deadlift_kg": "max"
}).reset_index()

  sex  best3squat_kg  best3bench_kg  best3deadlift_kg
0   F          322.5          235.0             270.5
1   M          490.0          415.0             420.0

In [16]:
#Рекорды каждого дивизиона
powerlift.groupby('division').agg({
  "best3squat_kg": "max",
  "best3bench_kg": "max",
  "best3deadlift_kg": "max"
}).reset_index()

       division  best3squat_kg  best3bench_kg  best3deadlift_kg
0         Heavy          432.0          330.0             382.5
1       Juniors          450.0          375.0             377.5
2         Light          325.5          217.5             315.0
3     Masters 1          405.0          345.0             395.0
4     Masters 2          365.0          310.5             335.0
5     Masters 3          300.0          260.0             305.0
6     Masters 4          235.0          220.0             260.5
7        Middle          370.0          268.5             345.0
8          Open          490.0          415.0             407.5
9   Sub-Juniors          370.0          310.0             335.0
10        Super          465.0          360.0             387.5
11   SuperHeavy          475.0          405.0             420.0

In [26]:
#Промотр уникальных 
powerlift['place'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  0,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [5]:
#Заменяем нечисловые значения
powerlift['place'] = powerlift['place'].replace(['DD','DQ','G'],'0')

In [9]:
#Возвращает новый DataFrame, в котором типы данных были изменены на тип int
powerlift['place'] = powerlift['place'].astype('int')

In [10]:
#Выводим в новый DataFrame участников занявшие первые места
powerlift1 = powerlift[powerlift['place'] == 1]
powerlift1

,name,sex,event,equipment,age,age_class,division,bodyweight_kg,weight_class_kg,best3squat_kg,best3bench_kg,best3deadlift_kg,place,date,federation,meet_name
0,Hiroyuki Isagawa,M,SBD,Single-ply,NaN,NaN,NaN,67.5,67.5,205,140,225,1,1985-08-03,IPF,World Games
7,Claudio Ardini,M,SBD,Single-ply,31.5,24-34,NaN,90,90,295,215,335,1,1985-08-03,IPF,World Games
13,Tony Stevens,M,SBD,Single-ply,NaN,NaN,NaN,NaN,90+,355,225,350,1,1985-08-03,IPF,World Games
17,Andrzej Stanaszek,M,B,Raw,21.5,20-23,NaN,51,52,NaN,157.5,NaN,1,1993-12-12,IPF,World Bench Press Championships
24,Markus Schick,M,B,Single-ply,17,16-17,NaN,54.5,56,NaN,147.5,NaN,1,1993-12-12,IPF,World Bench Press Championships
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41085,Lee Rorie,M,B,Single-ply,30.5,24-34,Open,86.6,90,NaN,235,NaN,1,1995-06-25,IPF,World Bench Press Championships
41101,Günter Königer,M,B,Single-ply,28.5,24-34,Open,98,100,NaN,240,NaN,1,1995-06-25,IPF,World Bench Press Championships
41114,Piet Faber,M,B,Single-ply,32.5,24-34,Open,109.5,110,NaN,247.5,NaN,1,1995-06-25,IPF,World Bench Press Championships
41128,Karl Saliger,M,B,Single-ply,25.5,24-34,Open,124.7,125,NaN,265,NaN,1,1995-06-25,IPF,World Bench Press Championships
41135,James Henderson #1,M,B,Raw,29.5,24-34,Open,150.5,125+,NaN,285,NaN,1,1995-06-25,IPF,World Bench Press Championships

In [28]:
#С помощью pivot table суммируем победы для каждого учасника
powerlift_first_p = pd.pivot_table(
    powerlift1,index = 'name',
    values = 'place',
    aggfunc = sum)
powerlift_first_p.sort_values(by = 'place', ascending = False)

                   place
name
Hideaki Inaba         28
Andrzej Stanaszek     24
Sergey Fedosienko     24
Ielja Strik           22
Hiroyuki Isagawa      21
...                  ...
Jarmo Ranta            1
Jarmo Sohlman          1
Jaroslav Halač         1
Jason Johnson          1
Štěpánka Židová        1

[3328 rows x 1 columns]

In [ ]:
#Сохраняем в csv файл
powerlift_first_p.to_csv('powerlift_first_p.csv')

In [25]:
#С помощью pivot table выводим для каждой комбинации подразделения и пола участника с наибольшим количеством побед 
#среди участников
pd.pivot_table(powerlift1,
               index=['division','sex','name'],
               values='place',
               aggfunc=np.sum)

                                    place
division   sex name
Heavy      F   Ana Rosa Castellain      2
               Larysa Soloviova         1
               Lisa Sjöstrand           1
               Marina Kudinova          1
               Svetl Miklasevich        1
...                                   ...
Super      F   Olena Kozlova            1
           M   Andrey Konovalov #1      1
               Michael Tuchscherer      1
SuperHeavy F   Bonica Brown             1
           M   Oleksiy Rokochyy Jr      1

[3881 rows x 1 columns]

In [15]:
#Импортируем  библиотеку pymysql для работы с базами данных SQL
import pymysql

In [23]:
#Подключаемся к нужной базе данных
conn=pymysql.connect(host='localhost',port=int(3306),user='root',passwd='root',db='course')

In [27]:
#Выполняем с помощью pandas последний запрос из финального проектапо SQL
df=pd.read_sql_query("SELECT s.* FROM ( SELECT teacher_no, course_no, student_name, email, birth_date FROM students GROUP BY teacher_no, course_no, student_name, email, birth_date HAVING COUNT(*) > 1 ) AS s1 JOIN students AS s ON (s.teacher_no = s1.teacher_no AND s.course_no = s1.course_no AND s.student_name = s1.student_name AND s.email = s1.email AND s.birth_date = s1.birth_date) ",conn)
df

C:\python\lib\site-packages\pandas\io\sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

   student_no teacher_no course_no student_name              email  birth_date
0           1          2      e001      Sadio M  sad1234@gmaol.com  2001-12-12
1           8          2      e001      Sadio M  sad1234@gmaol.com  2001-12-12
2           9          2      e001      Sadio M  sad1234@gmaol.com  2001-12-12
3          10          2      e001      Sadio M  sad1234@gmaol.com  2001-12-12